version: 2.1

jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-runner:latest
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          command: |
            set -xe
            whoami
            sudo whoami
            df -h
            pwd
            nproc --all
            free -mh
            docker pull fr3akyphantom/droid-builder:focal
          name: Prepare

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
