version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-runner:latest
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          command: |
            set -xe
            whoami
            sudo whoami
            df -h
            pwd
            nproc --all
            free -mh
            docker pull fr3akyphantom/droid-builder:focal
          name: Prepare
