version: 2.1

executors:
  worker:
    docker:
      # Primary Container, Just a playground
      - image: fr3akyphantom/droid-runner:latest
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"
      # Private Mirror Container
      - image: fr3akyphantom/mirror-bot:latest
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"

jobs:
  build:
    executor: worker
    resource_class: medium
    working_directory: /home/builder/
    steps:
      - run: |
          while true; do
            echo "." && sleep 300
          done

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: "prod"
          context: org-global
