version: 2.1

executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-runner:latest
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"

jobs:
  build:
    executor: worker
    resource_class: small
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 20.10.2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: "master"
          context: org-global
